name: Daglig bevakning

on:
  schedule:
    - cron: '0 8 * * *'  # Körs dagligen kl 08:00 UTC (09:00 svensk tid)
    - cron: '0 9 * * *'
    - cron: '0 10 * * *'
    - cron: '0 11 * * *'
    - cron: '0 12 * * *'
    - cron: '0 13 * * *'
    - cron: '0 14 * * *'
    - cron: '0 15 * * *'
    - cron: '0 16 * * *'
    - cron: '0 17 * * *'
    - cron: '0 18 * * *'
    - cron: '0 19 * * *'
    - cron: '0 20 * * *'
    - cron: '0 21 * * *'
    - cron: '0 22 * * *'
    - cron: '0 23 * * *'
    - cron: '0 7 * * *'
    - cron: '0 6 * * *'
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  check-water:
    runs-on: ubuntu-latest
    steps:
      - name: Klona repo
        uses: actions/checkout@v3

      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installera beroenden
        run: pip install -r requirements.txt

      - name: Kör bevattningsförbudsskript
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python script.py
