name: Daglig bevakning

on:
  schedule:
   - cron: '0 6 * 5 2'  # Körs dagligen kl 06:00 UTC (08:00 svensk tid)
   - cron: '0 6 * 5 4'  # Körs dagligen kl 06:00 UTC (08:00 svensk tid)
   - cron: '0 6 * 6 2'  # Körs dagligen kl 06:00 UTC (08:00 svensk tid)
   - cron: '0 6 * 6 4'  # Körs dagligen kl 06:00 UTC (08:00 svensk tid)
   - cron: '0 6 * 7 2'  # Körs dagligen kl 06:00 UTC (08:00 svensk tid)
   - cron: '0 6 * 7 4'  # Körs dagligen kl 06:00 UTC (08:00 svensk tid)
   - cron: '0 6 * 8 2'  # Körs dagligen kl 06:00 UTC (08:00 svensk tid)
   - cron: '0 6 * 8 4'  # Körs dagligen kl 06:00 UTC (08:00 svensk tid)
   - cron: '0 6 * 9 2'  # Körs dagligen kl 06:00 UTC (08:00 svensk tid)
   - cron: '0 6 * 9 4'  # Körs dagligen kl 06:00 UTC (08:00 svensk tid)  
  workflow_dispatch:

jobs:
  check-water:
    runs-on: ubuntu-latest
    steps:
      - name: Klona repo
        uses: actions/checkout@v3

      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installera beroenden
        run: pip install -r requirements.txt

      - name: Kör bevattningsförbudsskript
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python script.py
